yoda <- function() {
  quote <- c(
    "Fear is the path to the dark side. Fear leads to anger. Anger leads to hate. Hate leads to suffering.",
    "You must unlearn what you have learned",
    "Try not. Do or do not. There is no try",
    "We must wake",
    "When you look at the dark side, careful you must be, for the dark side looks back.",
    "Named must your fear be before vanish it you can.",
    "You will know good from bad when you are at peace and passive.",
    "Train yourself to let go of everything you fear to lose.",
    "Luminous beings are we, not this crude matter.",
    "Size matters not. Look at me. Judge me by my size, do you?",
    "Always pass on what you have learned.",
    "A Jedi uses the Force for knowlegde and defense, never for attack.",
    "You fail because you don't believe.",
    "If you end you training now, if you choose the quick and easy path as Vader did, you will become an agent of evil.",
    "Patience you must have",
    "The dark side clouds everything. Impossible to see the future is.",
    "Clear your mind.",
    "In the end, cowards are those who follow the dark side.",
    "Mind what you have learned. Save you it can.",
    "In this war, a danger there is of losing who we are.",
    "You will find only what you brind in.",
    "You must confront Vader. Then, only then, a Jedi will you be. An confront him you will.",
    "Smaller in number we are, but larger in mind.",
    "In a dark place we find ourselves, and a little more knowledge lights our way.",
    "A challenge lifelong it is, not to bend fear into anger.",
    "A Jedi must have the deepest commitment, the most serious mind. This one a long time have I watched. All his life has he looked away to the future, to the horizon. Never his mind on where he was. Hmm?",
    "Use your feelings, Obi-Wan, and find him you will.",
    "Difficult to see. Always in motion is the future.",
    "Control, control, you must learn control!",
    "Decide you must, how to serve them best. If you leave now, help them you could; but you would destroy all for which they have fought, and suffered.",
    "May the Force be with you",
    "Hmm. To a dark place this line of thought will carry us. Great care we must take.",
    "Through the Force, things you will see. Other places. The future, the past. Old friends long gone.",
    "To be Jedi is to face the truth, and choose. Give off light, or darkness, Padawan. Be a candle or the night.",
    "Much to learn you still hace my old padawan. This is just the beggining."
  )

  sample(quote, 1, replace = T)
}
